"use strict";
exports.__esModule = true;
var express_1 = require("express");
var RoomController_1 = require("./controllers/RoomController");
var SubjectController_1 = require("./controllers/SubjectController");
var UserController_1 = require("./controllers/UserController");
var routes = (0, express_1.Router)();
routes.post('/user', new UserController_1.UserController().create);
routes.post('/subject', new SubjectController_1.SubjectController().create);
routes.post('/room', new RoomController_1.RoomController().create);
routes.get('/room', new RoomController_1.RoomController().list);
routes.post('/room/:idRoom/create', new RoomController_1.RoomController().createVideo);
routes.post('/room/:idRoom/subject', new RoomController_1.RoomController().roomSubject);
exports["default"] = routes;
